arch: 
  - amd64
  
os: linux
dist: focal
service: docker

language: node_js
node_js: 12

before_script: chmod +x .travis/*.sh

script:
  - |
    set +e
    VERSION=e102e89946e3a47b27
    EXISTING_TAG=e102e89946e3a47b27
    if [[ -n ${EXISTING_TAG} ]]; then
      if [[ ${RECREATE_TAGS} == "true" ]]; then
        printf "[INFO] Removing tag for ${VERSION} version. New tag will be recreated during release."
        git push origin :$VERSION
      else
        printf "[ERROR] Cannot proceed with release - tag ${EXISTING_TAG} already exists."
        exit 1
      fi
    else
      printf "[INFO] No existing tags detected for $VERSION"
    fi
